# 05B-1. ECOS Macro Data Pipeline

## 목적

한국은행 ECOS Open API를 이용해
포트폴리오 모델의 Market Context에 사용할
거시경제 데이터를 수집하고 정제한다.

### 초기 대상

- USD/KRW 환율
- 한국은행 기준금리
- 국고채 3년물 금리

### 전체 흐름

ECOS API
→ Raw Data
→ Cleaning
→ Frequency / Date Alignment
→ Macro Feature
→ 05D Common Dataset에서 결합

In [1]:
# 05B-2. 환경 설정
# ECOS Macro Pipeline 기본 라이브러리 및 경로 설정

from pathlib import Path
import os

import pandas as pd
import requests

from dotenv import load_dotenv


PROJECT_ROOT = Path(
    r"C:\code\portfolio_optimization"
)

ECOS_RAW_DIR = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "ecos"
)

ECOS_RAW_DIR.mkdir(
    parents=True,
    exist_ok=True
)

load_dotenv(
    PROJECT_ROOT / ".env"
)

ECOS_API_KEY = os.getenv(
    "ECOS_API_KEY"
)

print(
    "Project root:",
    PROJECT_ROOT
)

print(
    "ECOS API key loaded:",
    bool(ECOS_API_KEY)
)

Project root: C:\code\portfolio_optimization
ECOS API key loaded: True

In [2]:
#05b-3. ecos api 기본 조회 함수
# 원천 데이터 수집 준비
# ECOS StatisticSearch 공통 조회 함수 생성

# 목적:
# - 환율 / 금리 등 여러 ECOS 통계를 동일한 방식으로 조회
# - API 오류를 명확하게 확인 

ECOS_BASE_URL = (
    "https://ecos.bok.or.kr"
    "/api/StatisticSearch"
)


def fetch_ecos_series(
    stat_code,
    frequency,
    start_date,
    end_date,
    item_code,
    start_index=1,
    end_index=10000
):

    url = (
        f"{ECOS_BASE_URL}"
        f"/{ECOS_API_KEY}"
        f"/json"
        f"/kr"
        f"/{start_index}"
        f"/{end_index}"
        f"/{stat_code}"
        f"/{frequency}"
        f"/{start_date}"
        f"/{end_date}"
        f"/{item_code}"
    )

    response = requests.get(
        url,
        timeout=30
    )

    print(
        "HTTP status:",
        response.status_code
    )

    response.raise_for_status()

    data = response.json()

    # ECOS 자체 오류 응답 처리
    if "RESULT" in data:

        raise RuntimeError(
            data["RESULT"]
        )

    rows = (
        data
        .get("StatisticSearch", {})
        .get("row", [])
    )

    return pd.DataFrame(
        rows
    )

In [3]:
#05b-4. 기준금리 test

# STAT_CODE  = 통계표 코드
# ITEM_CODE  = 통계 항목 코드
# D          = Daily, 일별

base_rate_test = fetch_ecos_series(
    stat_code="722Y001",
    frequency="D",
    start_date="20260101",
    end_date="20260915",
    item_code="0101000"
)

print(
    "Shape:",
    base_rate_test.shape
)

base_rate_test.head()

HTTP status: 200
Shape: (258, 14)

,STAT_CODE,STAT_NAME,ITEM_CODE1,ITEM_NAME1,ITEM_CODE2,ITEM_NAME2,ITEM_CODE3,ITEM_NAME3,ITEM_CODE4,ITEM_NAME4,UNIT_NAME,WGT,TIME,DATA_VALUE
0,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260101,2.5
1,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260102,2.5
2,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260103,2.5
3,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260104,2.5
4,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260105,2.5

In [5]:
#05b-5.기준금리 API 응답 필드 확인

print(
    base_rate_test.columns.tolist()
)

base_rate_test[
    [
        "STAT_CODE",
        "STAT_NAME",
        "ITEM_CODE1",
        "ITEM_NAME1",
        "UNIT_NAME",
        "TIME",
        "DATA_VALUE"
    ]
].head(10)

['STAT_CODE', 'STAT_NAME', 'ITEM_CODE1', 'ITEM_NAME1', 'ITEM_CODE2', 'ITEM_NAME2', 'ITEM_CODE3', 'ITEM_NAME3', 'ITEM_CODE4', 'ITEM_NAME4', 'UNIT_NAME', 'WGT', 'TIME', 'DATA_VALUE']

,STAT_CODE,STAT_NAME,ITEM_CODE1,ITEM_NAME1,UNIT_NAME,TIME,DATA_VALUE
0,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260101,2.5
1,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260102,2.5
2,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260103,2.5
3,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260104,2.5
4,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260105,2.5
5,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260106,2.5
6,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260107,2.5
7,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260108,2.5
8,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260109,2.5
9,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,연%,20260110,2.5

In [6]:
#05b-6. 전체 연구기간 기준금리 수집
#연구기간: 2018-02-05~2026-09-15

base_rate_raw = fetch_ecos_series(
    stat_code="722Y001",
    frequency="D",
    start_date="20180205",
    end_date="20260915",
    item_code="0101000"
)

print(
    "Shape:",
    base_rate_raw.shape
)

base_rate_raw.tail()

HTTP status: 200
Shape: (3145, 14)

,STAT_CODE,STAT_NAME,ITEM_CODE1,ITEM_NAME1,ITEM_CODE2,ITEM_NAME2,ITEM_CODE3,ITEM_NAME3,ITEM_CODE4,ITEM_NAME4,UNIT_NAME,WGT,TIME,DATA_VALUE
3140,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260911,3
3141,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260912,3
3142,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260913,3
3143,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260914,3
3144,722Y001,1.3.1. 한국은행 기준금리 및 여수신금리,0101000,한국은행 기준금리,None,None,None,None,None,None,연%,None,20260915,3

In [7]:
#05b-7. raw 기준금리 raw data 저장
#raw layer:
# - 컬럼명 변경 전
# - 값 변환 전
# - API 원본 형태 보존

BASE_RATE_RAW_PATH = (
    ECOS_RAW_DIR
    / "bok_base_rate_raw.csv"
)

base_rate_raw.to_csv(
    BASE_RATE_RAW_PATH,
    index=False,
    encoding="utf-8-sig"
)

print(
    "Saved:",
    BASE_RATE_RAW_PATH
)

Saved: C:\code\portfolio_optimization\data\raw\ecos\bok_base_rate_raw.csv

In [9]:
#05b-8. 기준금리 데이터 정제
#필요한 컬럼만 선택, 타입 변환

#time -> date
#data_value -> base_rate

base_rate_clean = (
    base_rate_raw[
        [
            "TIME",
            "DATA_VALUE"
        ]
    ]
    .copy()
)

base_rate_clean = (
    base_rate_clean
    .rename(
        columns={
            "TIME": "date",
            "DATA_VALUE": "base_rate"
        }
    )
)

base_rate_clean["date"] = pd.to_datetime(
    base_rate_clean["date"],
    format="%Y%m%d"
)

base_rate_clean["base_rate"] = pd.to_numeric(
    base_rate_clean["base_rate"],
    errors="coerce" #숫자로 못 바꾸는 값 -> 결측값으로 
)

base_rate_clean = (
    base_rate_clean
    .sort_values("date")
    .reset_index(drop=True)
)

base_rate_clean.head()

        date  base_rate
0 2018-02-05        1.5
1 2018-02-06        1.5
2 2018-02-07        1.5
3 2018-02-08        1.5
4 2018-02-09        1.5

In [10]:
#05b-9. 기준금리 정제 결과 확인
#목적: 기간, 결측치, 중복날짜 확인

print(
    "Start:",
    base_rate_clean["date"].min()
)

print(
    "End:",
    base_rate_clean["date"].max()
)

print(
    "Rows:",
    len(base_rate_clean)
)

print(
    "Missing values:",
    base_rate_clean["base_rate"].isna().sum()
)

print(
    "Duplicate dates:",
    base_rate_clean["date"].duplicated().sum()
)

base_rate_clean.tail()

Start: 2018-02-05 00:00:00
End: 2026-09-15 00:00:00
Rows: 3145
Missing values: 0
Duplicate dates: 0

           date  base_rate
3140 2026-09-11        3.0
3141 2026-09-12        3.0
3142 2026-09-13        3.0
3143 2026-09-14        3.0
3144 2026-09-15        3.0